#!/bin/bash

APP_NAME=notion-desktop
ELECTRON_VERSION=11.4.1
NOTION_VERSION=2.0.15
PACKAGE_REVISION=0
ENHANCER_VERSION=0.10.2
BUILD_ARCH=x64
PACKAGE_ARCH=$1

export APP_NAME ELECTRON_VERSION NOTION_VERSION PACKAGE_REVISION ENHANCER_VERSION BUILD_ARCH PACKAGE_ARCH
